package tui

// helpContent is the hand-maintained table behind the ? help window: every
// key binding in the TUI, grouped by context. The key column is the first
// whitespace-delimited field; /-separated alternates (e.g. "q/ctrl+c") are
// matched individually by the footer drift guard (help_test.go).
func helpContent() []contentLine {
	h := func(s string) contentLine { return contentLine{text: s, heading: true} }
	r := func(key, desc string) contentLine {
		return contentLine{text: padRight(key, 16) + desc}
	}
	return []contentLine{
		h("Global"),
		r("p", "pull (SmartPull: autostash, ff/rebase decisions)"),
		r("P", "push the current branch (sets upstream)"),
		r("s", "switch to the selected branch (SmartSwitch); if it's in another worktree, offers to jump there"),
		r("S", "open the stash window (list all stashes)"),
		r("u", "undo the last commit (soft, ref-only)"),
		r("g", "bookmark quick-switcher: jump to / compare / paste a bookmarked file (the . menu on any file offers Bookmark this file and Compare against bookmark — pick a bookmark, then diff the focused file against it). In it (navigation-first): ↑↓/jk move, enter jumps (diffs the bookmark vs the working-tree file), p pastes to a typed path, m marks one then a second to compare, c compares the highlighted bookmark against a shelf entry, x removes (confirms), / filters, ? shows the key list, esc closes"),
		r("G", "shelf quick-switcher: the . menu on any file also offers Compare against shelf. In it (navigation-first): ↑↓/jk move, enter diffs the entry vs the working-tree file, p restores to a typed path, m marks one then a second to compare two entries, c compares the highlighted entry against a bookmark, x removes (confirms), / filters, ? shows the key list, esc closes"),
		r("w", "worktree popup for the selected existing branch"),
		r("W", "worktree popup on a new templated branch"),
		r("m", "mark a row; m on a second row opens the pair-op picker"),
		r("R", "repo switcher popup"),
		r(",", "settings (agent skill install)"),
		r(".", "action menu — context actions for the selected row and panel (incl. copy actions)"),
		r("", "Compare against working dir (.-menu): on any focused commit/staged/shelf file, diffs that version against the same path in the working tree"),
		r("o", "cycle the focused panel's sort order"),
		r("z", "cycle the focused window's text display (cutoff / wrap / scroll)"),
		r("shift+←/→", "scroll display mode: pan the focused window horizontally"),
		r("/", "filter the focused panel"),
		r("tab/shift+tab", "cycle panel focus forward / backward"),
		r("←/→", "focus the left column / the Commits panel"),
		r("ctrl+←/→", "cycle the focused tab slot: top (Branches / Remotes / Worktrees) or middle (Files / Tags)"),
		r("click", "focus the window under the cursor and select the clicked row"),
		r("wheel", "scroll the list under the cursor ([ui] wheel_step rows; files view: tree or commits)"),
		r("↑/k ↓/j", "move the selection"),
		r("pgup/pgdn", "page the selection (25% of the viewport)"),
		r("esc", "clear the mark, then the active filter"),
		r("c", "commit the staged index (title + description popup)"),
		r("C", "amend the last commit (edit message / fold in staged changes)"),
		r("r", "reload all panels"),
		r("?", "this help window"),
		r("q/ctrl+c", "quit"),
		h("Branches panel"),
		r("b", "create a branch off the selected one (popup)"),
		r("B", "create a branch and switch to it"),
		r("d", "delete the selected branch"),
		r(".", "rename branch / copy branch name / Solo this branch / Add to commit view / Go to tip in commits (.-menu)"),
		r("", "Solo this branch (.-menu): scope the Commits panel to this branch (re-run to un-solo); Add/Remove from commit view builds a multi-branch set; Show all branches clears it; Go to tip in commits jumps the Commits cursor to this branch's tip"),
		h("Remotes panel"),
		r("c", "checkout: create or fast-forward a local tracking branch (stay on the current branch)"),
		r("s", "checkout and switch to it — fast-forward-safe; refuses if the local branch has diverged"),
		r("f", "fetch all remotes (updates tracking refs and the behind-counts)"),
		r(".", "Prune (.-menu): drop tracking refs for branches deleted upstream"),
		r(".", "copy remote branch name (.-menu)"),
		h("Worktrees panel"),
		r("enter", "switch into the selected worktree"),
		r("d", "remove the selected worktree"),
		h("Tags panel"),
		r("", "a tab in the middle (Files) box — ctrl+←/→ switches Files ⇄ Tags; ● annotated, ○ lightweight"),
		r("enter", "jump the Commits cursor to the tag's target commit"),
		r(".", "Check out tag (.-menu): detached HEAD, a new branch at the tag, or a new worktree (branch + dir prefilled from the tag name)"),
		r(".", "Delete tag (.-menu): delete the selected tag after a confirm"),
		h("Shelf panel"),
		r("", "frozen, non-git per-file copies (the default bucket); add via the . menu anywhere a file is focused"),
		r("enter", "diff the shelved copy against the current working-tree file"),
		r("m", "mark an entry; mark a second to compare the two shelved copies side-by-side"),
		r(".", "Restore to… (writes the copy to a path you type) / Remove from shelf"),
		h("Files panel"),
		r("space", "stage the selected working-tree file (git add)"),
		r("H", "stage hunks: open the region/line staging picker"),
		r("s", "stash changes: popup to name + pick files (ctrl+s confirms)"),
		r("m", "mark / unmark a file (multi-select for stashing)"),
		r("enter", "side-by-side diff of the unstaged change (index → working tree)"),
		r("h", "file history: commits that touched it (left) + per-commit diff (right)"),
		r("b", "blame: who last changed each line, grouped by commit"),
		r("d", "discard the marked files (or the cursor row): revert edits, delete new files (confirm)"),
		r("D", "discard ALL unstaged changes: revert every edit + delete every new file (confirm)"),
		r(".", "on an untracked file: Add to .gitignore (this file, anchored) / Add extension to .gitignore (*.ext) — appends to the repo-root .gitignore"),
		r(".", "Edit in editor: open the selected file in $VISUAL/$EDITOR (vi/notepad fallback), then refresh"),
		h("Staged panel"),
		r("space", "unstage the selected file (git restore --staged)"),
		r("enter", "side-by-side diff of the staged change (HEAD → index)"),
		r("m", "mark / unmark a file; h history, b blame (as in Files)"),
		h("Conflict resolution process (x)"),
		r("x", "enter / resume the conflict process (when the repo is conflicted)"),
		r("↑/↓ j", "move between conflicted files"),
		r("enter", "pick hunks: open the line editor (both-modified files)"),
		r("C/i", "keep current / incoming (both-modified files)"),
		r("k/d/b", "keep modified / delete / keep base (modify-delete files)"),
		r("m", "mark resolved (after editing by hand)"),
		r("A", "mark all resolved"),
		r("c/a", "continue / abort the merge or rebase (once resolved)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("L/esc", "leave the process (resume later with x); esc in a running step cancels it"),
		h("Hunk picker (x conflict resolve / H stage)"),
		r("←/→", "switch the focused side (current ↔ incoming)"),
		r("↑/k ↓/j", "move the line cursor (steps across regions)"),
		r("space", "pick the cursor line (builds the result in pick order)"),
		r("c / i", "take the whole region from current / incoming"),
		r("C / I", "take all regions from current / incoming"),
		r("n / p", "jump to the next / previous region"),
		r("enter", "apply when every region is resolved"),
		r("esc", "cancel (close without resolving)"),
		h("Commits panel"),
		r("", "shows commits from ALL local branches by default, in date order, with a single-line commit graph (natural order only; hidden while filtering/sorting); header shows the mode — Commits (all) / Commits (solo: <branch>)"),
		r("", "the left column is the branch the commit is on: BRIGHT *current/branch on that branch's tip, grayed otherwise; long names trim with … (select to reveal the full name); the commit id shows in the status bar. Filtering still matches the full id and full branch name"),
		r("l", "show the selected commit's files in the left column"),
		r(".", "rename commit / copy commit id / Create branch here / Create worktree here / Cherry-pick here / Revert this commit / Reset to this commit (soft|mixed|hard) / Show all branches when soloed / Show as list|graph (.-menu)"),
		r("", "on a commit that is a branch's tip: Rename branch <name> / Delete branch <name> (.-menu) — one pair per local tip; delete is hidden for a checked-out branch"),
		r("", "Show as list / Show as graph (.-menu): flat ●-gutter list vs the lane graph; lane color marks each commit's line of development"),
		r("(scroll)", "more commits load automatically as you near the end"),
		h("Filter mode (/)"),
		r("↑/↓ pgup/pgdn", "move the selection through the filtered rows"),
		r("enter", "keep the filter and leave input mode"),
		r("esc", "cancel the filter"),
		r("backspace", "delete; any typed text narrows the list"),
		h("Worktree popup (w/W)"),
		r("enter/tab", "next input field / confirm"),
		r("e", "edit the previewed branch name (new-branch mode)"),
		r("w/enter", "create the worktree"),
		r("W", "create the worktree and switch to it"),
		r("esc", "cancel"),
		h("Branch popup (b/B)"),
		r("enter", "create the branch"),
		r("esc", "cancel"),
		h("Pair-op popup (m on a second row)"),
		r("↑/k ↓/j", "choose an operation (Branches: merge, rebase, interactive rebase)"),
		r("enter", "run the operation (clears the mark)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "close, keeping the mark"),
		h("Interactive rebase editor"),
		r("p / r / s / d", "set the row action: pick / reword / squash / drop"),
		r("ctrl+↑/↓", "move the focused commit up / down"),
		r("↑/k ↓/j", "move the cursor"),
		r("enter", "start the rebase with the current plan"),
		r("R", "reset every row to pick, original order"),
		r("esc", "cancel (close without rebasing)"),
		h("Commit files view (l)"),
		r("←/→ tab", "switch focus between the file tree and the commit list"),
		r("↑/k ↓/j", "move on the focused side (commits side reloads the tree)"),
		r("pgup/pgdn", "page the focused side"),
		r("ctrl+↑/↓", "scroll the file tree from either side (wheel: 3)"),
		r("/", "search the focused side: file paths (tree) or the commit list (commits side); enter keeps it, esc cancels"),
		r("enter", "diff of the selected file in this commit (tree side)"),
		r("h", "history of the selected file (tree side)"),
		r("b", "blame of the selected file (tree side)"),
		r("esc", "clear the search, then close"),
		r("l", "close"),
		h("Stash window (S)"),
		r("↑/k ↓/j", "move the stash selection"),
		r("pgup/pgdn", "page the stash list"),
		r("l", "open the file tree for the stash (then ←/→ focus tree/list, like commit files)"),
		r("enter", "stash actions: apply / pop / drop (drop confirms; [z] mode in the menu)"),
		r("S/esc", "close the stash window"),
		h("Diff view (enter)"),
		r("↑/k ↓/j", "scroll one line"),
		r("pgup/pgdn", "scroll one screen"),
		r("n/p", "next / previous change (also ctrl+↓/↑)"),
		r("f", "toggle full file ↔ changed lines only"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("← → 0", "scroll mode: pan left / right / reset"),
		r("h", "history of this file at the shown revision"),
		r("b", "blame of this file at the shown revision"),
		r("esc", "close"),
		r("ctrl+c", "quit"),
		h("History view (h)"),
		r("↑/k ↓/j", "move between commits (the diff updates on the right)"),
		r("b", "blame the file at the selected commit"),
		r("esc/h", "back"),
		r("ctrl+c", "quit"),
		h("Blame view (b)"),
		r("↑/k ↓/j", "move the line cursor"),
		r("pgup/pgdn", "move the cursor one screen"),
		r("enter", "file history at the commit under the cursor"),
		r("esc/b", "back"),
		r("ctrl+c", "quit"),
		h("Repo switcher (R)"),
		r("enter", "switch to the selected repository"),
		r("ctrl+d", "forget the selected repository"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "close (type to filter)"),
		h("Action menu (.)"),
		r("(key)", "run the action with that key; lists context actions only (row + panel)"),
		r("↑/k ↓/j", "move; enter runs the highlighted action"),
		r("/", "filter the list by name (enter keeps, esc cancels)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "close"),
		r("copy", "Copy commit id (Commits); Copy file path / file name (Files/Staged) — OSC 52"),
		h("Settings (,)"),
		r("↑/↓", "move between entries"),
		r("enter", "open the agent picker / install checked skills"),
		r("space", "toggle the selected agent skill (picker)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "back to the menu, then close"),
		h("Decision modal"),
		r("↑/k ↓/j", "choose an option"),
		r("enter", "confirm the option"),
		r("esc", "abort the operation"),
		h("Help window (?)"),
		r("/", "search (enter keeps it, esc cancels)"),
		r("↑/k ↓/j", "scroll by 1 (ctrl+↑/↓: by 5; mouse wheel: 3)"),
		r("pgup/pgdn", "scroll by a page"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "clear the search, then close"),
		r("q/enter", "close"),
	}
}
