package tui

// helpContent is the hand-maintained table behind the ? help window: every
// key binding in the TUI, grouped by context. The key column is the first
// whitespace-delimited field; /-separated alternates (e.g. "q/ctrl+c") are
// matched individually by the footer drift guard (help_test.go).
func helpContent() []contentLine {
	h := func(s string) contentLine { return contentLine{text: s, heading: true} }
	r := func(key, desc string) contentLine {
		return contentLine{text: padRight(key, 16) + desc}
	}
	return []contentLine{
		h("Global"),
		r("p", "pull (SmartPull: autostash, ff/rebase decisions). On the Branches panel, a non-current branch pulls in the background (stay here): ff its ref, pull in its worktree, or stash→switch→pull→switch-back. Slow ops confirm first (y/n; disable with [ui] disable_slow_op_confirm)."),
		r("P", "push the current branch (sets upstream)"),
		r("", "Push <branch> (.-menu on the Branches panel): push the highlighted branch (sets upstream) — works for any local branch, current or not, including one never pushed before; no checkout needed"),
		r("", "Force push <branch> (.-menu on the Branches panel, current branch): force-push the current branch — a modal offers force-with-lease (refuses if the remote moved under you) or force (overwrites the remote unconditionally); esc aborts"),
		r("s", "switch to the selected branch (SmartSwitch); if it's in another worktree, offers to jump there. Confirms first (y/n)."),
		r("S", "open the stash window (list all stashes)"),
		r("u", "undo the last commit (soft, ref-only)"),
		r("g", "bookmark quick-switcher: jump to / compare / paste a bookmarked file (the . menu on any file offers Bookmark this file and Compare against bookmark — pick a bookmark, then diff the focused file against it). In it (navigation-first): ↑↓/jk move, enter jumps (diffs the bookmark vs the working-tree file), e opens the bookmarked file in your external editor (read-only), p pastes to a typed path, t copies to a new dir under <repo>.tmp (works for file AND commit bookmarks), m marks one then a second to compare, c compares the highlighted bookmark against a shelf entry, x removes (confirms), / filters, ? shows the key list, esc closes"),
		r("G", "shelf quick-switcher: the . menu on any file also offers Compare against shelf. In it (navigation-first): ↑↓/jk move, enter diffs the entry vs the working-tree file, e opens the shelved copy in your external editor (read-only), p restores to a typed path, t copies to a new dir under <repo>.tmp, m marks one then a second to compare two entries, c compares the highlighted entry against a bookmark, x removes (confirms), / filters, ? shows the key list, esc closes"),
		r("!", "notification center: health recommendations for this repo (e.g. write a commit-graph on a big repo — makes commit browsing ~10× faster). ↑↓ select, enter shows a notice's actions, esc closes. 'Not now' asks again next load; 'Never for this repo' is remembered in prompts.toml"),
		r("F", "fuzzy file finder: opens a picker over every tracked file; press / then type a query (fvgo → files_view.go) to filter by path, ↑↓/pgup/pgdn to move, enter to open a per-file menu (View content, Diff HEAD↔working tree, History, Blame, Open in editor, Copy path), esc closes"),
		r("w", "worktree popup for the selected existing branch"),
		r("W", "worktree popup on a new templated branch. In the popup, p picks a saved branch prefix (Settings → Branch prefixes), fills any <user:…> labels, and seeds the editable name"),
		r("m", "mark a row; m on a second row opens the pair-op picker"),
		r("R", "repo switcher popup (navigation-first: ↑↓/jk/pgup/pgdn move, / filters, enter switches — while filtering, the first enter locks the filter)"),
		r(",", "settings (agent skill install)"),
		r(".", "action menu — context actions for the selected row and panel (incl. copy actions)"),
		r("ctrl+p", "command palette — generic command launcher (↑↓/jk move, enter runs, esc closes); currently: Show commit"),
		r("#", "show commit by SHA: type a commit-ish (SHA / ref); enter resolves it and opens that commit's files in the files-view"),
		r("", "Compare against working dir / Copy to working dir (.-menu): on any focused stash/commit/staged file, diffs that version against the same path in the working tree (Compare) or writes it into the working tree at its own path (Copy)"),
		r("o", "cycle the focused panel's sort order"),
		r("z", "cycle the focused window's text display (cutoff / wrap / scroll)"),
		r("t", "maximize the focused left-column panel to fill the whole left column (t again restores); while maximized, ctrl+←/→ still cycles that slot's tabs"),
		r("T", "fullscreen the focused panel — any left-column panel or Commits — to fill the whole screen (T or esc restores; t drops back to the left column)"),
		r("shift+←/→", "scroll display mode: pan the focused window horizontally"),
		r("/", "filter the focused panel"),
		r("ctrl+r", "clear the focused window's filtering — its / filter, or on the Commits panel the @ highlight and the \\ commit filter (other windows' filters are left untouched)"),
		r("alt+↑/↓", "recall previous searches (history dropdown) while typing in the / filter, @ highlight, or the bookmark/shelf/files-tree search"),
		r("tab/shift+tab", "cycle panel focus forward / backward"),
		r("←/→", "focus the left column / the Commits panel"),
		r("ctrl+←/→", "cycle the focused tab slot: top (Branches / Remotes / Worktrees), middle (Files / Tags), or bottom (Staged / Reflog)"),
		r("click", "focus the window under the cursor and select the clicked row"),
		r("wheel", "scroll the list under the cursor ([ui] wheel_step rows; files view: tree or commits)"),
		r("↑/k ↓/j", "move the selection"),
		r("pgup/pgdn", "page the selection (25% of the viewport)"),
		r("esc", "clear the mark, then the active filter"),
		r("c", "commit the staged index (title + description popup)"),
		r("C", "amend the last commit (edit message / fold in staged changes)"),
		r("r", "reload all panels (keeps them visible while refreshing)"),
		r("?", "this help window"),
		r("q/ctrl+c", "quit"),
		h("Branches panel"),
		r("b", "create a branch off the selected one (popup). In the popup, ctrl+p picks a saved branch prefix (Settings → Branch prefixes) and seeds the name"),
		r("B", "create a branch and switch to it"),
		r("d", "delete the selected branch"),
		r("p", "on a non-current branch: pull it in the background (stay on your branch) — same as the .-menu 'Pull <branch> (stay here)'"),
		r(".", "rename branch / copy branch name / Pull <branch> (stay here) / Solo this branch / Add to commit view / Go to tip in commits (.-menu)"),
		r("", "Solo this branch (.-menu): scope the Commits panel to this branch (re-run to un-solo); Add/Remove from commit view builds a multi-branch set; Show all branches clears it; Go to tip in commits jumps the Commits cursor to this branch's tip"),
		h("Remotes panel"),
		r("c", "checkout: create or fast-forward a local tracking branch (stay on the current branch)"),
		r("s", "checkout and switch to it — fast-forward-safe; refuses if the local branch has diverged"),
		r("f", "fetch all remotes (updates tracking refs and the behind-counts)"),
		r(".", "Prune (.-menu): drop tracking refs for branches deleted upstream"),
		r(".", "copy remote branch name (.-menu)"),
		h("Worktrees panel"),
		r("enter", "switch into the selected worktree"),
		r("d", "remove the selected worktree"),
		h("Tags panel"),
		r("", "a tab in the middle (Files) box — ctrl+←/→ switches Files ⇄ Tags; ● annotated, ○ lightweight; ▲ marks tags that exist on the default remote (origin or first remote) — local-only or not-yet-checked tags show no marker (deliberately indistinguishable before a lookup runs)"),
		r("enter", "jump the Commits cursor to the tag's target commit"),
		r(".", "Check out tag (.-menu): detached HEAD, a new branch at the tag, or a new worktree (branch + dir prefilled from the tag name)"),
		r(".", "Push tag (.-menu): push the tag to a remote (auto when only one, else pick)"),
		r(".", "Delete tag (.-menu): delete the selected tag after a confirm"),
		r(".", "Refresh remote status (.-menu): one-shot git ls-remote --tags; updates the ▲ marker for every visible tag; errors shown on the status line; for background auto-refresh see [refresh] remote_tags"),
		h("Shelf panel"),
		r("", "frozen, non-git per-file copies (the default bucket); add via the . menu anywhere a file is focused"),
		r("enter", "diff the shelved copy against the current working-tree file"),
		r("m", "mark an entry; mark a second to compare the two shelved copies side-by-side"),
		r(".", "Restore to… (writes the copy to a path you type) / Remove from shelf"),
		h("Reflog panel"),
		r("", "a tab in the bottom-left (Staged) box — ctrl+←/→ switches Staged ⇄ Reflog; lists the HEAD reflog (read-only), newest first"),
		r("enter / l", "open the entry's commit in the files view (changed files vs parent; even for dangling commits)"),
		r(".", "Copy SHA / Bookmark this commit / Shelf this commit (name it) (compare via the g switcher)"),
		r(".", "Reset to this entry (.-menu): move the current branch here (soft/mixed/hard) / Check out this entry (detached or as a new branch you switch to)"),
		h("Files panel"),
		r("space", "stage the marked files (or the cursor row) — git add"),
		r("H", "stage hunks: open the region/line staging picker"),
		r("s", "stash changes: popup to name + pick files (ctrl+s confirms)"),
		r("m", "mark / unmark a file (multi-select for staging, stashing, discarding)"),
		r("enter", "side-by-side diff of the unstaged change (index → working tree)"),
		r("h", "file history: commits that touched it (left) + per-commit diff (right)"),
		r("b", "blame: who last changed each line, grouped by commit"),
		r("d", "discard the marked files (or the cursor row): revert edits, delete new files (confirm)"),
		r("D", "discard ALL unstaged changes: revert every edit + delete every new file (confirm)"),
		r(".", "on an untracked file: Add to .gitignore (this file, anchored) / Add extension to .gitignore (*.ext) — appends to the repo-root .gitignore"),
		r(".", "Edit in editor: open the selected file in $VISUAL/$EDITOR (vi/notepad fallback), then refresh"),
		h("Staged panel"),
		r("space", "unstage the marked files (or the cursor row) — git restore --staged"),
		r("enter", "side-by-side diff of the staged change (HEAD → index)"),
		r(".", "Open staged version in external editor: open the index blob (the staged copy, distinct from the working file) in $VISUAL/$EDITOR, read-only"),
		r("m", "mark / unmark a file; h history, b blame (as in Files)"),
		h("Conflict resolution process (x)"),
		r("x", "enter / resume the conflict process (when the repo is conflicted)"),
		r("↑/↓ j", "move between conflicted files"),
		r("enter", "pick hunks: open the line editor (both-modified files)"),
		r("C/i", "keep current / incoming (both-modified files)"),
		r("k/d/b", "keep modified / delete / keep base (modify-delete files)"),
		r("m", "mark resolved (after editing by hand)"),
		r("A", "mark all resolved"),
		r("c/a", "continue / abort the merge or rebase (once resolved)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("L/esc", "leave the process (resume later with x); esc in a running step cancels it"),
		h("Hunk picker (x conflict resolve / H stage)"),
		r("←/→", "switch the focused side (current ↔ incoming)"),
		r("↑/k ↓/j", "move the line cursor (steps across regions)"),
		r("space", "pick the cursor line (builds the result in pick order)"),
		r("c / i", "take the whole region from current / incoming"),
		r("C / I", "take all regions from current / incoming"),
		r("n / p", "jump to the next / previous region"),
		r("enter", "apply when every region is resolved"),
		r("esc", "cancel (close without resolving)"),
		h("Commits panel"),
		r("", "shows commits from ALL local branches by default, in date order, with a single-line commit graph (natural order only; hidden while filtering/sorting); header shows the mode — Commits (all) / Commits (solo: <branch>)"),
		r("", "the left column is the branch the commit is on: BRIGHT *current/branch on that branch's tip, grayed otherwise; long names trim with … (select to reveal the full name); the commit id shows in the status bar. Filtering still matches the full id and full branch name"),
		r("↓ ↑", "in the Commits graph, ↓ marks a local branch's tip and ↑ the tip of its tracked remote (both together = local and remote in sync)"),
		r("l", "show the selected commit's files in the left column (focus stays on the commit list)"),
		r("enter", "drill into the selected commit's files: open the files view AND move focus to the file tree (l + focus tree)"),
		r("i", "view the selected commit's full message in a scrollable popup; also works while the files view is open (the popup layers over the tree, esc returns to it)"),
		r("I", "open the selected commit's message in the external editor ($EDITOR, read-only)"),
		r("", "uncommitted work shows as ◇ Working tree / ◇ Staged rows atop the graph (only when dirty); l/enter diffs them (working tree vs index, index vs HEAD); commit-only actions are unavailable on them"),
		r("", "the ◇ Working tree / ◇ Staged rows can be added (m) to the ◉ compare selection like commits — Compare selection then diffs a commit against your working copy or index"),
		r("@", "highlight search: keep all commits visible, dim non-matches (graph stays); ctrl+↑/↓ jump prev/next match; enter keeps, esc clears"),
		r("ctrl+f", "Commits: eager search — if the active / filter or @ highlight query isn't in the loaded commits, page history to find it and jump to it (asks before scanning deeper)"),
		r("ctrl+l", "Commits: load the next batch of commits now (without scrolling to the end)"),
		r("home/end", "jump to the top / bottom of the focused list; End on Commits also loads the next batch"),
		r("\\", "filter commits by path / author / message / date (popup; empty fields clear that axis, ctrl+r clears all fields); graph hides while filtered"),
		r("m", "add / remove the selected commit (or ◇ Working tree / ◇ Staged row) to the ◉ compare selection; the . menu then drives Compare selection or Squash"),
		r("space", "mark / unmark the selected commit for compare — the same ◉ set as m but capped at two: the second space-mark opens the comparison immediately (with 2 already marked, space a marked one to unmark first; esc clears ALL marks, or . → Unmark all commits). Re-opening the comparison already on screen keeps it (no reload)"),
		r(".", "view message / open message in editor / rename commit / copy commit id / Create branch here / Create worktree here / Cherry-pick here / Revert this commit / Reset to this commit (soft|mixed|hard) / Compare against working tree / Compare against staged / Export commit as patch / Add to compare selection (space) / Unmark commit / Unmark all commits / Compare selection / Squash N commits / Drop N selected commits / Show all branches when soloed / Show as list|graph (.-menu)"),
		r("", "Compare against working tree / Compare against staged (.-menu): open the files view as a whole-tree diff of this commit vs your working copy / the index; enter on a file diffs that path"),
		r("shift+↑/↓", "grow the ◉ compare selection (a contiguous run of commits)"),
		r("", "Compare selection (.-menu): toggle commits into the ◉ set (m / Add to compare selection / shift+↑↓), then Compare selection — 2 = the diff between them, 3+ = the combined diff of the range (oldest^..newest, refused from a root commit); Unmark all commits (N) empties it"),
		r("", "Squash N commits (.-menu): with 2+ commits in the ◉ set, combine the selected commits into one (messages concatenated; reword afterward). When they aren't adjacent, a prompt offers Reorder & squash — the skipped in-between commits move to just after the squash. Off-branch selections are refused; conflicts pause for `git rebase --continue`"),
		r("", "Drop N selected commits (.-menu): with 2+ commits in the ◉ set, delete them all in one interactive rebase (no adjacency needed; gaps stay). Off-branch / working-tree-or-staged selections are refused; conflicts pause for `git rebase --continue`. Drop commit (no set) drops just the cursor commit"),
		r("", "on a commit that is a branch's tip: Rename branch <name> / Delete branch <name> (.-menu) — one pair per local tip; delete is hidden for a checked-out branch"),
		r("", "on a non-merge commit of the current branch: Move commit up (newer) / Move commit down (older) / Drop commit (.-menu) — one-step interactive rebase; conflicts pause for `git rebase --continue`"),
		r("", "Show as list / Show as graph (.-menu): flat ●-gutter list vs the lane graph; lane color marks each commit's line of development"),
		r("< / >", "narrow / widen the commit graph window (in lanes); a ⋯ marks lanes beyond each edge"),
		r("shift+←/→", "pan the commit graph window left / right"),
		r("=", "snap the commit graph window to the selected commit's node"),
		r("(scroll)", "more commits load automatically as you near the end"),
		h("Filter mode (/)"),
		r("↑/↓ pgup/pgdn", "move the selection through the filtered rows"),
		r("enter", "keep the filter and leave input mode"),
		r("esc", "cancel the filter"),
		r("backspace", "delete; any typed text narrows the list"),
		h("Worktree popup (w/W)"),
		r("enter/tab", "next input field / confirm"),
		r("e", "edit the previewed branch name (new-branch mode)"),
		r("w/enter", "create the worktree"),
		r("W", "create the worktree and switch to it"),
		r("esc", "cancel"),
		h("Branch popup (b/B)"),
		r("enter", "create the branch"),
		r("esc", "cancel"),
		h("Pair-op popup (m on a second row)"),
		r("↑/k ↓/j", "choose an operation (Branches: merge, rebase, interactive rebase)"),
		r("enter", "run the operation (clears the mark)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "close, keeping the mark"),
		h("Interactive rebase editor"),
		r("p / r / s / d", "set the row action: pick / reword / squash / drop"),
		r("ctrl+↑/↓", "move the focused commit up / down"),
		r("↑/k ↓/j", "move the cursor"),
		r("enter", "start the rebase with the current plan"),
		r("R", "reset every row to pick, original order"),
		r("esc", "cancel (close without rebasing)"),
		h("Commit files view (l)"),
		r("←/→ tab", "switch focus between the file tree and the commit list"),
		r("↑/k ↓/j", "move on the focused side (commits side reloads the tree)"),
		r("pgup/pgdn", "page the focused side"),
		r("ctrl+↑/↓", "scroll the file tree from either side (wheel: 3)"),
		r("/", "search the focused side: file paths (tree) or the commit list (commits side); enter keeps it, esc cancels"),
		r("enter", "tree side: diff of the selected file (changed-files mode vs parent; all-files mode vs the working tree). Commit-list side: drill in — move focus to the file tree"),
		r("a", "toggle all files: every file in the commit's tree (as if checked out) vs only the files it changed"),
		r(".", "tree side: View file — show the file's content at this commit (no diff) in the right pane ([↑/↓] scroll, [z] view mode, [esc] close, [←] back to the tree); Open in external editor — open that content in $VISUAL/$EDITOR, read-only"),
		r("i", "view the underlying commit's full message in a popup over the tree (esc returns; commit views only, not stash/compare)"),
		r("h", "history of the selected file (tree side)"),
		r("b", "blame of the selected file (tree side)"),
		r(".", "commits side: the full Commits-panel menu (cherry-pick / revert / reset / create branch|worktree|tag / compare / …); tree side: copy path/name"),
		r("< > = shift+←/→", "commits side: narrow / widen / snap / pan the commit graph window (same as the Commits panel)"),
		r("esc", "clear the search, then close"),
		r("l", "close"),
		h("Stash window (S)"),
		r("↑/k ↓/j", "move the stash selection"),
		r("pgup/pgdn", "page the stash list"),
		r("l", "open the file tree for the stash (then ←/→ focus tree/list, like commit files)"),
		r("enter", "stash actions: apply / pop / drop (drop confirms; [z] mode in the menu)"),
		r("S/esc", "close the stash window"),
		h("Diff view (enter)"),
		r("↑/k ↓/j", "scroll one line"),
		r("pgup/pgdn", "scroll one screen"),
		r("n/p", "next / previous change (also ctrl+↓/↑; press again at the end/start to wrap around)"),
		r("N/P", "from the last / first change, press twice to step to the next / previous file in the list (a bottom-left cue advertises it; a notice names the new file)"),
		r("home/end", "jump to top / bottom of the file; at the edge a bottom-left cue appears and pressing it again steps to the previous / next file in the list (a notice names the new file)"),
		r("f", "toggle full file ↔ changed lines only"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("← → 0", "scroll mode: pan left / right / reset"),
		r("h", "history of this file at the shown revision"),
		r("b", "blame of this file at the shown revision"),
		r(".", "export this file's diff as patch"),
		r("esc", "close"),
		r("ctrl+c", "quit"),
		h("History view (h)"),
		r("↑/k ↓/j", "move between commits (the diff updates on the right)"),
		r("enter", "open the selected commit's diff full-screen (esc returns)"),
		r("b", "blame the file at the selected commit"),
		r("e", "open the selected commit's version of the file in your external editor (read-only)"),
		r("esc/h", "back"),
		r("ctrl+c", "quit"),
		h("Blame view (b)"),
		r("↑/k ↓/j", "move the line cursor"),
		r("pgup/pgdn", "move the cursor one screen"),
		r("enter", "file history at the commit under the cursor"),
		r("e", "open the blamed file (at this revision) in your external editor (read-only)"),
		r("esc/b", "back"),
		r("ctrl+c", "quit"),
		h("Repo switcher (R)"),
		r("enter", "switch to the selected repository"),
		r("ctrl+d", "forget the selected repository"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "close (type to filter)"),
		h("Action menu (.)"),
		r("(key)", "run the action with that key; lists context actions only (row + panel)"),
		r("↑/k ↓/j", "move; enter runs the highlighted action"),
		r("/", "filter the list by name (enter keeps, esc cancels)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "close"),
		r("copy", "Copy commit id / commit title (Commits); Copy file path / file name (Files/Staged) — OSC 52"),
		h("Settings (,)"),
		r("↑/↓", "move between entries"),
		r("enter", "open the agent picker / install checked skills"),
		r("space", "toggle the selected agent skill (picker)"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "back to the menu, then close"),
		h("Decision modal"),
		r("↑/k ↓/j", "choose an option"),
		r("enter", "confirm the option"),
		r("esc", "abort the operation"),
		h("Help window (?)"),
		r("/", "search (enter keeps it, esc cancels)"),
		r("↑/k ↓/j", "scroll by 1 (ctrl+↑/↓: by 5; mouse wheel: 3)"),
		r("pgup/pgdn", "scroll by a page"),
		r("z", "cycle text display: cutoff / wrap / scroll"),
		r("esc", "clear the search, then close"),
		r("q/enter", "close"),
	}
}
